### ISSUE TITLE
CJ Node dead.

### ISSUE THREAD

**Issue by DarrenOfficial** [DarrenOfficial/lavalink-list#32]
@ThnksCJ Your node is down, therefore it's removed from the list. If you have fixed the issue, feel free to make another pull request.

**Comment by ThnksCJ** [comment]
Ye both of them are down my entire server has gone down I'm getting it back but asap

**Comment by DarrenOfficial** [comment]
👍

**Comment by ThnksCJ** [comment]
The nodes are both back up do could you add them back to the list please

**Comment by DarrenOfficial** [comment]
go make pr, im outside rn
