### ISSUE TITLE
API Servers.json

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [DarrenOfficial/lavalink-list#51]
https://scpcl.site/servers.json
Is that good enough indentifiers or i need to edit them? (If yes i will put it to repo from my site)

**Comment by DarrenOfficial** [comment]
It's uhh, not great cause there's spaces and `'` which may cause some issue

**Comment by DarrenOfficial** [comment]
also i suggest setting the identifier to all lowercase and just based it off the domain name

**Comment by MrMasrozYTLIVE** [comment]
Ok
I'll do it when i will return from school
